added few lines ready to merge
barclays-training-delete/team-work pull request #1
Opened 2021-09-16 06:52 UTC by shubham15gupta09

This is PR is for testing. 
It's ready to merge

2021-09-16 06:53 UTC, adithnaveen requested changes
three is a change in need

2021-09-16 06:53 UTC, adithnaveen commented on README.md
> +# Hi , I am SHubham
there is a space before ","

2021-09-16 06:56 UTC, shubham15gupta09 commented on README.md
> +# Hi , I am SHubham
I have done the changes.
I think it is ready to merge

2021-09-16 06:56 UTC, shubham15gupta09 commented
raising the new PR

2021-09-16 06:57 UTC, adithnaveen approved these changes
approved for main Line

2021-09-16 06:58 UTC, merged

2022-02-05 17:51 UTC, shubham15gupta09 commented
ok